apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-git
  template:
    metadata:
      labels:
        app: nginx-git
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ["/bin/sh", "-c"]
        args:
        - git clone --depth=1 https://github.com/HASHTAG-YOU/argocd-test.git /web-root &&
          cp -r /web-root/* /mnt/web-root/
        volumeMounts:
        - name: web-root
          mountPath: /mnt/web-root
      volumes:
      - name: web-root
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-git-service
spec:
  selector:
    app: nginx-git
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
