apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: git-clone
          image: alpine:3.14
          command: ["/bin/sh", "-c"]
          args:
            - "apk add --no-cache git && git clone https://github.com/HASHTAG-YOU/argocd-test.git /usr/share/nginx/html"
          volumeMounts:
            - mountPath: /usr/share/nginx/html  # Nginx에 클론할 경로
            name: html-volume
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: /usr/share/nginx/html  # Nginx의 기본 웹 경로
              name: html-volume
      volumes:
        - name: html-volume
          emptyDir: {}  # Git 클론 결과물을 저장할 임시 디렉토리

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # 서비스가 제공할 포트 (클러스터 내부에서 접근하는 포트)
      targetPort: 80   # Nginx 컨테이너의 포트 (기본 80)
  type: NodePort   # 외부 접근을 위한 LoadBalancer 타입 서비스 (혹은 NodePort)
